/**
 * Author:  bruno
 * Created: Dec 10, 2015
 */

-- MySQL Script generated by MySQL Workbench
-- Qui 10 Dez 2015 18:23:43 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zf2_base
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zf2_base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zf2_base` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `zf2_base` ;

-- -----------------------------------------------------
-- Table `zf2_base`.`zf2_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zf2_base`.`zf2_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `activation_key` VARCHAR(255) NOT NULL,
  `updated_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
